# JJW 3/9/17
#
# 3 versions:
#  - prod & staging w/postgres & nginx (separate memcache or redis?)
#  - dev w/no nginx 
#  - local dev w/no pg either (just forward)

web:
  restart: always
  build: .
  #expose:
  #  - "8000"
  ports:
    - 8000:8000
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /home/joe/eracks11:/home/joe/eracks11
    #- /usr/src/app
    #- /usr/src/app/static
  #env_file: .env
  #command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
  #command: /usr/bin/python /home/joe/eracks11/manage.py runserver 0:8000
  #command: /home/joe/eracks11/manage.py runserver 0:8000
  #command: sudo netstat -antp
  command: cd /home/joe/eracks11/ && python manage.py runserver 0.0.0.0:8000
  #entrypoint: ["bash", "ls", "-l"]
  #entrypoint: /usr/bin/python

nginx:
  restart: always
  #build: ./nginx/
  image: nginx:latest
  ports:
    - 80:80
    - 443:443
  volumes:
    - /www/static
    - /home/joe/eracks11/conf/etc/nginx.conf:/etc/nginx.conf
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  expose:
    - 5432
  ports:
    - 5432:5432
  #volumes:
  #  - pgdata:/var/lib/postgresql/data/
  #links:
  #  - web:web

redis:
  restart: always
  image: redis:latest
  ports:
    - 6379:6379
  #volumes:
  #  - redisdata:/data
