calist=[('', 'Select CA County'),
 ("(9.5,'Alameda')", 'Alameda 9.5%'),
 ("(10.0,'Alameda.Albany_Hayward_SanLeandro_UnionCity')",
  'Alameda (Albany, Hayward, San Leandro, Union City) 10%'),
 ("(7.5,'Alpine')", 'Alpine 7.5%'),
 ("(8.0,'Amador')", 'Amador 8%'),
 ("(7.5,'Butte')", 'Butte 7.5%'),
 ("(8.0,'Butte.Paradise')", 'Butte (Paradise) 8%'),
 ("(7.5,'Calaveras')", 'Calaveras 7.5%'),
 ("(7.5,'Colusa')", 'Colusa 7.5%'),
 ("(8.0,'Colusa.Williams')", 'Colusa (Williams) 8%'),
 ("(8.5,'Contra Costa')", 'Contra Costa 8.5%'),
 ("(9.0,'Contra Costa.Antioch_Concord_Hercules_Orinda_Pittsburg')",
  'Contra Costa (Antioch, Concord, Hercules, Orinda, Pittsburg) 9%'),
 ("(10.0,'Contra Costa.ElCerrito')", 'Contra Costa (El Cerrito) 10%'),
 ("(9.5,'Contra Costa.Moraga_Pinole_RheemValley_Richmond')",
  'Contra Costa (Moraga, Pinole, Rheem Valley, Richmond) 9.5%'),
 ("(9.3,'Contra Costa.SanPablo')", 'Contra Costa (San Pablo) 9.3%'),
 ("(7.8,'Del Norte')", 'Del Norte 7.8%'),
 ("(7.5,'El Dorado')", 'El Dorado 7.5%'),
 ("(8.0,'El Dorado.Placerville_SouthLakeTahoe')",
  'El Dorado (Placerville, South Lake Tahoe) 8%'),
 ("(8.2,'Fresno')", 'Fresno 8.2%'),
 ("(9.2,'Fresno.Huron')", 'Fresno (Huron) 9.2%'),
 ("(8.7,'Fresno.Reedley_Selma')", 'Fresno (Reedley, Selma) 8.7%'),
 ("(9.0,'Fresno.Sanger')", 'Fresno (Sanger) 9%'),
 ("(7.5,'Glenn')", 'Glenn 7.5%'),
 ("(8.0,'Humboldt')", 'Humboldt 8%'),
 ("(8.8,'Humboldt.Arcata_Eureka_Trinidad')",
  'Humboldt (Arcata, Eureka, Trinidad) 8.8%'),
 ("(9.0,'Humboldt.RioDell')", 'Humboldt (Rio Dell) 9%'),
 ("(8.0,'Imperial')", 'Imperial 8%'),
 ("(8.5,'Imperial.Calexico')", 'Imperial (Calexico) 8.5%'),
 ("(8.0,'Inyo')", 'Inyo 8%'),
 ("(7.5,'Kern')", 'Kern 7.5%'),
 ("(8.5,'Kern.Arvin_Delano')", 'Kern (Arvin, Delano) 8.5%'),
 ("(8.3,'Kern.ChinaLakeNWC_Ridgecrest')",
  'Kern (China Lake NWC, Ridgecrest) 8.3%'),
 ("(7.5,'Kings')", 'Kings 7.5%'),
 ("(7.5,'Lake')", 'Lake 7.5%'),
 ("(8.0,'Lake.Clearlake_ClearlakeHighlands_ClearlakePark_Lakeport')",
  'Lake (Clearlake, Clearlake Highlands, Clearlake Park, Lakeport) 8%'),
 ("(7.5,'Lassen')", 'Lassen 7.5%'),
 ("(9.0,'Los Angeles')", 'Los Angeles 9%'),
 ("(9.5,'Los Angeles.Avalon_CityofCommerce_Commerce_CulverCity_ElMonte_Inglewood_SanFernando_SantaMonica_SouthElMonte')",
  'Los Angeles (Avalon, City of Commerce, Commerce, Culver City, El Monte, Inglewood, San Fernando, Santa Monica, South El Monte) 9.5%'),
 ("(10.0,'Los Angeles.BiolaCollege_LaMirada_PicoRivera_SouthGate')",
  'Los Angeles (Biola College, La Mirada, Pico Rivera, South Gate) 10%'),
 ("(8.0,'Madera')", 'Madera 8%'),
 ("(8.5,'Marin')", 'Marin 8.5%'),
 ("(9.0,'Marin.CorteMadera_Fairfax_Greenbrae_HamiltonA.F.B._Ignacio_Larkspur_Novato_SanAnselmo_Sausalito')",
  'Marin (Corte Madera, Fairfax, Greenbrae, Hamilton A.F.B., Ignacio, Larkspur, Novato, San Anselmo, Sausalito) 9%'),
 ("(9.3,'Marin.SanRafael')", 'Marin (San Rafael) 9.3%'),
 ("(8.0,'Mariposa')", 'Mariposa 8%'),
 ("(7.6,'Mendocino')", 'Mendocino 7.6%'),
 ("(8.6,'Mendocino.FortBragg')", 'Mendocino (Fort Bragg) 8.6%'),
 ("(8.1,'Mendocino.PointArena_Ukiah_Willits')",
  'Mendocino (Point Arena, Ukiah, Willits) 8.1%'),
 ("(7.5,'Merced')", 'Merced 7.5%'),
 ("(8.0,'Merced.Atwater_Gustine_LosBanos_Merced')",
  'Merced (Atwater, Gustine, Los Banos, Merced) 8%'),
 ("(7.5,'Modoc')", 'Modoc 7.5%'),
 ("(7.5,'Mono')", 'Mono 7.5%'),
 ("(8.0,'Mono.MammothLakes')", 'Mono (Mammoth Lakes) 8%'),
 ("(7.6,'Monterey')", 'Monterey 7.6%'),
 ("(8.6,'Monterey.Carmel_DelMonteGrove_FortOrd_FortOrd_Greenfield_Marina_Monterey_PacificGrove_PresidioofMonterey_SandCity_Seaside_Soledad_U.S.NavalPostgradSchool')",
  'Monterey (Carmel, Del Monte Grove, Fort Ord, Fort Ord, Greenfield, Marina, Monterey, Pacific Grove, Presidio of Monterey, Sand City, Seaside, Soledad, U.S. Naval Postgrad School) 8.6%'),
 ("(9.1,'Monterey.DelReyOaks_Salinas')",
  'Monterey (Del Rey Oaks, Salinas) 9.1%'),
 ("(8.1,'Monterey.Gonzales_KingCity')", 'Monterey (Gonzales, King City) 8.1%'),
 ("(8.0,'Napa')", 'Napa 8%'),
 ("(7.6,'Nevada')", 'Nevada 7.6%'),
 ("(8.1,'Nevada.GrassValley')", 'Nevada (Grass Valley) 8.1%'),
 ("(8.5,'Nevada.NevadaCity')", 'Nevada (Nevada City) 8.5%'),
 ("(8.4,'Nevada.Truckee')", 'Nevada (Truckee) 8.4%'),
 ("(8.0,'Orange')", 'Orange 8%'),
 ("(8.5,'Orange.LaHabra')", 'Orange (La Habra) 8.5%'),
 ("(9.0,'Orange.Stanton')", 'Orange (Stanton) 9%'),
 ("(7.5,'Placer')", 'Placer 7.5%'),
 ("(7.5,'Plumas')", 'Plumas 7.5%'),
 ("(8.0,'Riverside')", 'Riverside 8%'),
 ("(9.0,'Riverside.CathedralCity_Coachella_PalmSprings_SmokeTree')",
  'Riverside (Cathedral City, Coachella, Palm Springs, Smoke Tree) 9%'),
 ("(8.0,'Sacramento')", 'Sacramento 8%'),
 ("(8.5,'Sacramento.Galt_GoldRiver_Mather_RanchoCordova_Sacramento')",
  'Sacramento (Galt, Gold River, Mather, Rancho Cordova , Sacramento) 8.5%'),
 ("(7.5,'San Benito')", 'San Benito 7.5%'),
 ("(8.5,'San Benito.Hollister')", 'San Benito (Hollister) 8.5%'),
 ("(8.3,'San Benito.SanJuanBautista')", 'San Benito (San Juan Bautista) 8.3%'),
 ("(8.0,'San Bernardino')", 'San Bernardino 8%'),
 ("(8.3,'San Bernardino.Montclair_NortonA.F.B._SanBernardino')",
  'San Bernardino (Montclair, Norton A.F.B., San Bernardino) 8.3%'),
 ("(8.0,'San Diego')", 'San Diego 8%'),
 ("(8.5,'San Diego.ElCajon_Vista')", 'San Diego (El Cajon, Vista) 8.5%'),
 ("(8.8,'San Diego.LaMesa')", 'San Diego (La Mesa) 8.8%'),
 ("(9.0,'San Diego.NationalCity')", 'San Diego (National City) 9%'),
 ("(8.8,'San Francisco')", 'San Francisco 8.8%'),
 ("(8.0,'San Joaquin')", 'San Joaquin 8%'),
 ("(9.0,'San Joaquin.Lathrop_Stockton')",
  'San Joaquin (Lathrop, Stockton) 9%'),
 ("(8.5,'San Joaquin.Manteca_Tracy')", 'San Joaquin (Manteca, Tracy) 8.5%'),
 ("(7.5,'San Luis Obispo')", 'San Luis Obispo 7.5%'),
 ("(8.0,'San Luis Obispo.ArroyoGrande_Atascadero_DelMarHeights_GroverBeach_MorroBay_PasoRobles_PismoBeach_SanLuisObispo_ShellBeach')",
  'San Luis Obispo (Arroyo Grande, Atascadero, Del Mar Heights, Grover Beach, Morro Bay, Paso Robles, Pismo Beach, San Luis Obispo, Shell Beach) 8%'),
 ("(9.0,'San Mateo')", 'San Mateo 9%'),
 ("(9.5,'San Mateo.HalfMoonBay')", 'San Mateo (Half Moon Bay) 9.5%'),
 ("(9.3,'San Mateo.Hillsdale_SanMateo')",
  'San Mateo (Hillsdale, San Mateo) 9.3%'),
 ("(8.0,'Santa Barbara')", 'Santa Barbara 8%'),
 ("(8.3,'Santa Barbara.Guadalupe_SantaMaria')",
  'Santa Barbara (Guadalupe, Santa Maria) 8.3%'),
 ("(8.8,'Santa Clara')", 'Santa Clara 8.8%'),
 ("(9.0,'Santa Clara.Campbell')", 'Santa Clara (Campbell) 9%'),
 ("(8.3,'Santa Cruz')", 'Santa Cruz 8.3%'),
 ("(8.8,'Santa Cruz.Capitola_SantaCruz_ScottsValley_Seabright')",
  'Santa Cruz (Capitola, Santa Cruz, Scotts Valley, Seabright) 8.8%'),
 ("(9.0,'Santa Cruz.Freedom_Watsonville')",
  'Santa Cruz (Freedom, Watsonville) 9%'),
 ("(7.5,'Shasta')", 'Shasta 7.5%'),
 ("(8.0,'Shasta.Anderson')", 'Shasta (Anderson) 8%'),
 ("(7.5,'Sierra')", 'Sierra 7.5%'),
 ("(7.5,'Siskiyou')", 'Siskiyou 7.5%'),
 ("(7.8,'Siskiyou.MountShasta')", 'Siskiyou (Mount Shasta) 7.8%'),
 ("(7.6,'Solano')", 'Solano 7.6%'),
 ("(8.6,'Solano.Benicia_Fairfield_MareIsland_TravisA.F.B._Vallejo')",
  'Solano (Benicia, Fairfield, Mare Island, Travis A.F.B., Vallejo) 8.6%'),
 ("(8.4,'Solano.RioVista')", 'Solano (Rio Vista) 8.4%'),
 ("(7.9,'Solano.Vacaville')", 'Solano (Vacaville) 7.9%'),
 ("(8.3,'Sonoma')", 'Sonoma 8.3%'),
 ("(9.3,'Sonoma.Cotati')", 'Sonoma (Cotati) 9.3%'),
 ("(8.8,'Sonoma.Healdsburg_RohnertPark_SantaRosa_Sonoma')",
  'Sonoma (Healdsburg, Rohnert Park, Santa Rosa, Sonoma) 8.8%'),
 ("(9.0,'Sonoma.Sebastopol')", 'Sonoma (Sebastopol) 9%'),
 ("(7.6,'Stanislaus')", 'Stanislaus 7.6%'),
 ("(8.1,'Stanislaus.Ceres_Oakdale')", 'Stanislaus (Ceres, Oakdale) 8.1%'),
 ("(7.5,'Sutter')", 'Sutter 7.5%'),
 ("(7.5,'Tehama')", 'Tehama 7.5%'),
 ("(7.8,'Tehama.RedBluff')", 'Tehama (Red Bluff) 7.8%'),
 ("(7.5,'Trinity')", 'Trinity 7.5%'),
 ("(8.0,'Tulare')", 'Tulare 8%'),
 ("(8.8,'Tulare.Dinuba')", 'Tulare (Dinuba) 8.8%'),
 ("(8.5,'Tulare.Farmersville_Porterville_Tulare')",
  'Tulare (Farmersville, Porterville, Tulare) 8.5%'),
 ("(8.3,'Tulare.Visalia')", 'Tulare (Visalia) 8.3%'),
 ("(7.5,'Tuolumne')", 'Tuolumne 7.5%'),
 ("(8.0,'Tuolumne.Sonora')", 'Tuolumne (Sonora) 8%'),
 ("(7.5,'Ventura')", 'Ventura 7.5%'),
 ("(8.0,'Ventura.Naval_Oxnard_PortHueneme')",
  'Ventura (Naval, Oxnard, Port Hueneme) 8%'),
 ("(7.5,'Yolo')", 'Yolo 7.5%'),
 ("(8.0,'Yolo.Broderick_Bryte_WestSacramento')",
  'Yolo (Broderick, Bryte, West Sacramento) 8%'),
 ("(8.5,'Yolo.Davis')", 'Yolo (Davis) 8.5%'),
 ("(8.3,'Yolo.Woodland')", 'Yolo (Woodland) 8.3%'),
 ("(7.5,'Yuba')", 'Yuba 7.5%'),
 ("(8.0,'Yuba.Wheatland')", 'Yuba (Wheatland) 8%')]